### ISSUE TITLE
Compare Controller without cerebellum, controller + static cerebellum, and controller + plastic cerebellum

### ISSUE THREAD

**Issue by alberto-antonietti** [near-nes/controller#10]
# Generate a comparison between different configurations of the controller

### final times:
network: 0:00:05.089255
brain.py: 0:00:28.129874

![Image](https://github.com/user-attachments/assets/30d760b3-d13f-4eef-b190-bf4c52af9cd4)

<details>

<summary>all plots</summary>

![Image](https://github.com/user-attachments/assets/a75af3dd-e6e7-4887-990b-4721788591df)
![Image](https://github.com/user-attachments/assets/c532a9fb-80f7-4d98-80e7-b05bf1f82170)
![Image](https://github.com/user-attachments/assets/620ce705-fa78-4550-a000-644731bc6630)
![Image](https://github.com/user-attachments/assets/e4cc563f-89d5-4929-92ac-1cac97c57bd6)
![Image](https://github.com/user-attachments/assets/d3169f8a-d84f-44bb-ac3a-f02ce7c4e529)
![Image](https://github.com/user-attachments/assets/51a34f1e-a0b6-4e59-aea0-b7c009e7285f)
![Image](https://github.com/user-attachments/assets/fe3c0356-d757-40c4-b8df-f472e428d2ee)
![Image](https://github.com/user-attachments/assets/570fe8eb-0810-416e-87d8-6b3d7634712e)
![Image](https://github.com/user-attachments/assets/27bb3eb4-d5a9-4f97-9493-a599c023171e)
![Image](https://github.com/user-attachments/assets/9fa74395-017a-41fc-9d66-b8e8fb5bbfa2)

</details>

## Test 2- Controller with static cerebellum

<details>

<summary>Time: 0:05:38</summary>

### final times:
cerebellum: 0:00:37.536319
network: 0:00:40.742875
brain.py: 0:05:38.632381

### different results
note: i got different results on different runs. I did NOT note down with how many VPs i started the first attempt. In the second:
`mpirun -np 8 music complete.music`
cerebellum: 0:00:23.750482
network: 0:00:26.088180
brain.py: 0:02:48.692521

### parameters:
```yaml
name: No plasticity (inverse)
simulations:
  basal_activity:
    connection_models:
      parallel_fiber_to_purkinje_plus:
        synapse:
          Aplus: 0
          Aminus: 0
      parallel_fiber_to_stellate:
        synapse:
          Aplus: 0
          Aminus: 0
      parallel_fiber_to_basket:
        synapse:
          Aplus: 0
          Aminus: 0
      parallel_fiber_to_purkinje_minus:
        synapse:
          Aplus: 0
          Aminus: 0

name: No plasticity (forward)
simulations:
  basal_activity:
    connection_models:
      parallel_fiber_to_purkinje_plus:
        synapse:
          Aplus: 0
          Aminus: 0
      parallel_fiber_to_stellate:
        synapse:
          Aplus: 0
          Aminus: 0
      parallel_fiber_to_basket:
        synapse:
          Aplus: 0
          Aminus: 0
      parallel_fiber_to_purkinje_minus:
        synapse:
          Aplus: 0
          Aminus: 0
```
</details>

![Image](https://github.com/user-attachments/assets/61d98b8c-3da8-4574-b7ef-b7c7297ddd6f)

<img width="1091" alt="Image" src="https://github.com/user-attachments/assets/8318a6f4-1a8f-48e2-9893-9535cb9548e3" />
<img width="1093" alt="Image" src="https://github.com/user-attachments/assets/395a6baf-d4e6-41f0-a975-949d92252091" />

<details>

<summary>other plots</summary>

![Image](https://github.com/user-attachments/assets/3da210b0-5f0c-450f-8492-4b809caa5c16)
![Image](https://github.com/user-attachments/assets/469c2082-0299-4659-8b42-87d725d83067)
![Image](https://github.com/user-attachments/assets/75f7e9f8-0ce7-4c58-8cf9-ff05f9ca03d4)
![Image](https://github.com/user-attachments/assets/9d1ec809-7ee8-461a-b074-f2d6db241285)
![Image](https://github.com/user-attachments/assets/7817b436-1ad1-484c-bbb2-3f51cc687121)
![Image](https://github.com/user-attachments/assets/a5f3b9fd-859d-4836-8c6a-72098bde9079)
![Image](https://github.com/user-attachments/assets/1e279ef0-bf4f-4fff-aba9-cb20a069efa0)
![Image](https://github.com/user-attachments/assets/a77d185d-407a-48a2-beb6-d2f1ebea5000)
![Image](https://github.com/user-attachments/assets/f78323f7-0515-4402-9f1e-ba479380c346)
![Image](https://github.com/user-attachments/assets/14dd0a08-350d-44ca-bf4d-3c7dbfffcc8f)
![Image](https://github.com/user-attachments/assets/817d44c7-26e9-48ba-b24a-57bd29502c1c)
![Image](https://github.com/user-attachments/assets/358c7e37-1b19-4863-bb0d-b630ebaf9d1d)

</details>

## Test 3 - Controller with plastic cerebellum
<details>

<summary>Time: 0:05:17</summary>

### final times:
cerebellum: 0:00:37.020744
network: 0:00:39.875374
brain.py: 0:05:17.418356

### different results
note: i got different results on different runs. I did NOT note down with how many VPs i started the first attempt. In the second:
`mpirun -np 8 music complete.music`
cerebellum: 0:00:24.309195
network: 0:00:26.439763
brain.py: 0:02:40.837553

### parameters:
```yaml
name: No plasticity (forward)
simulations:
  basal_activity:
    connection_models:
      parallel_fiber_to_purkinje_plus:
        synapse:
          Aplus: 0.0002
          Aminus: -0.0001
      parallel_fiber_to_stellate:
        synapse:
          Aplus: 0.0002
          Aminus: -0.0001
      parallel_fiber_to_basket:
        synapse:
          Aplus: 0.00005
          Aminus: -0.00002
      parallel_fiber_to_purkinje_minus:
        synapse:
          Aplus: 0.0002
          Aminus: -0.0001

name: No plasticity (inverse)
simulations:
  basal_activity:
    connection_models:
      parallel_fiber_to_purkinje_plus:
        synapse:
          Aplus: 0.0002
          Aminus: -0.0001
      parallel_fiber_to_stellate:
        synapse:
          Aplus: 0.0002
          Aminus: -0.0001
      parallel_fiber_to_basket:
        synapse:
          Aplus: 0.00005
          Aminus: -0.00002
      parallel_fiber_to_purkinje_minus:
        synapse:
          Aplus: 0.0002
          Aminus: -0.0001
```
</details>

![Image](https://github.com/user-attachments/assets/c5bc735e-bc2d-40d2-8a3a-3b947b35cf8e)

<img width="1093" alt="Image" src="https://github.com/user-attachments/assets/bdc29812-1d37-4e99-9d11-c4236035d6de" />

<img width="1091" alt="Image" src="https://github.com/user-attachments/assets/8a17e508-fcdf-4e90-8593-408a30c74e9e" />

<details>

<summary>other plots</summary>

![Image](https://github.com/user-attachments/assets/ff337a13-f11f-4361-86b8-5949c2b4dddd)
![Image](https://github.com/user-attachments/assets/e4a28cab-b1ff-48bc-a8cc-7699adf35a95)
![Image](https://github.com/user-attachments/assets/06c31fdf-c9d3-4f87-98c6-9c2ffec35a03)
![Image](https://github.com/user-attachments/assets/3f6fbb96-2fc2-4442-83ce-ffc37bb06049)
![Image](https://github.com/user-attachments/assets/5b8d05a7-81c4-4bcd-a41e-875d4b7954e7)
![Image](https://github.com/user-attachments/assets/a26477bc-b40a-4951-8498-64dc55c94ea1)
![Image](https://github.com/user-attachments/assets/699cf383-1755-45cb-b76e-f242edc2ad3b)
![Image](https://github.com/user-attachments/assets/92bec2b9-4dfd-46bc-8537-f1a7c3149c10)
![Image](https://github.com/user-attachments/assets/a38ddd88-b3d3-4d47-9a0b-ef17c0295328)
![Image](https://github.com/user-attachments/assets/b81c2da4-31a3-4795-a985-4e29a9118f9e)
![Image](https://github.com/user-attachments/assets/70dbd0a0-c7ec-4205-991c-29f2f3e89fac)

</details>

For each Test report:
1 Trial (1 trajectory, 650 ms)
- Plot desired and actual trajectory
- Rasterplots of all blocks
- Report the time needed for the simulation
